options:
	prefix: SkUltimateChat
	prefix-msg: %{SkUltimateChat-commandes-prefix}%
	perms: perm.%{SkUltimateChat-permisssions-prefix}%
	#	from = le nom de la BDD, à définir dans le fichier de config ?
	from: `%{{@prefix}-sql.database}%`.`SkUltimateChat`
#

#	loaded 	= pack activées
#	chat	= chat définis sur émojis
#	enable	= emoji mode on, mais pas forcément loaded donc pas chat

#	Function by Snow-Pyon
function packetRPSend(player: player, url: text, hash: text = ""):
    set {_packet} to new play_server_resource_pack_send packet
    set string pinfo 0 of {_packet} to {_url}
    if {_hash} = "":
        set string pinfo 1 of {_packet} to ("%hashed {_url} using ""SHA-1""%") #Need of SkUtilities.
    send {_player} packet {_packet}
#

on packet recieve:
	if event-string is "PacketPlayInResourcePackStatus":
		set {_player} to event-player
		set {_status} to packet field "status"
		if "%{_status}%" = "SUCCESSFULLY_LOADED":
			send "{@prefix} <gold>Émojies &2chargées." to {_player}
			set {{@prefix}.emoji.chat.%player%} to true
			set {{@prefix}.emoji.loaded.%player%} to true
		else if "%{_status}%" = "DECLINED":
			send "{@prefix} <light red>Erreur de chargement des émojis." to {_player}
			
#

on join:
	if {{@prefix}.emoji.enable.%player%} is true:
		packetRPSend(player, "https://www.dropbox.com/s/jjnuiuu70lngxmt/PWTG_Pack.zip?dl=0", "%{SkUltimateChat-hash}%")
#
on quit:
	delete {{@prefix}.emoji.loaded.%player%}
	delete {{@prefix}.emoji.chat.%player%}
#


command /emoji [<text>]:
	description: "Change vos préférances d'Emoji!"
	trigger:
		if {{@prefix}.emoji.module-emoji} is not true:
			stop trigger
		else if arg 1 is not set:
			send "&6--&2 Emoji &6--"
			send "&a/emoji &e<on / off / mode>"
			send "&eon&c: &fActive les emojis"
			send "&eoff&c: &fDésactive les emojis"
			send "&emode&c: &fActive/Désactive les emoji à chaque connexions"
			if {{@prefix}.emoji.loaded.%player%} is true:
				if {{@prefix}.emoji.emoji-list} is true:
					send "&eliste&c: &fAffiche la liste des émojis &c& &fpermet de les utiliser"
					send "   &c→→→ pour voir la liste il faut avoir les emoji &a[ON]&c←←←"
		else if arg 1 is "on":
			if {{@prefix}.emoji.wait.%player%} is true:
				send "&cMerci de patienter un peu avant de faire cette commande !"
				stop trigger
			set {{@prefix}.emoji.chat.%player%} to true
			if {{@prefix}.emoji.loaded.%player%} is not set:
				packetRPSend(player, "https://www.dropbox.com/s/jjnuiuu70lngxmt/PWTG_Pack.zip?dl=0", "%{SkUltimateChat-hash}%")
			set {{@prefix}.emoji.loaded.%player%} to true
			send "{@prefix-msg} &rVous avez activé les émojis, /emoji liste pour voir la liste."
			ChatSendFull(player)
			set {{@prefix}.emoji.wait.%player%} to true
			wait 30 seconds
			delete {{@prefix}.emoji.wait.%player%}
		else if arg 1 is "off":
			if {{@prefix}.emoji.wait.%player%} is true:
				send "&cMerci de patienter un peu avant de faire cette commande !"
				stop trigger
			delete {{@prefix}.emoji.chat.%player%}
			send "{@prefix-msg} &rVous avez désactivé les émojis."
			ChatSendFull(player)
			set {{@prefix}.emoji.wait.%player%} to true
			wait 30 seconds
			delete {{@prefix}.emoji.wait.%player%}
		else if arg 1 is "mode":
			if {{@prefix}.emoji.enable.%player%} is true:
				delete {{@prefix}.emoji.enable.%player%}
				send "{@prefix-msg} &cEmoji désactivé lors de votre prochainne connexion !"
				send "{@prefix-msg} &cPour les désactiver dès maintenant &e/emoji off"
			else:
				set {{@prefix}.emoji.enable.%player%} to true
				send "{@prefix-msg} &aLes emoji seronts activées à votre prochainne connexion !"
				send "{@prefix-msg} &2Pour les activer dès maintenant &e/emoji on"
		else if arg 1 is "liste" or "list":
			if {{@prefix}.emoji.emoji-list} is true:
				if {{@prefix}.emoji.loaded.%player%} is true:
					send "&6--&2 Emoji &6--"
					send "&6Shift&c' &6Cliquez sur une &bémoji&c, &6pour l'ajouter au message&c:"
					set {_count} to 0
					loop {{@prefix}-emoji::*}:
						add 1 to {_count}
					set {_loop} to 0
					loop {{@prefix}-emoji::*}:
						add 1 to {_loop}
						#if player has permission "{@prefix}.emoji.%loop-index%":  --> Fonction pour des permission d'émoji individuelle
						if {_loop} < {_count}:
							set {_tellraw.emoji.list} to "%{_tellraw.emoji.list}%,"
						set {_tellraw.emoji.list} to "%{_tellraw.emoji.list}%{""text"":""%loop-value%"",""insertion"":""%loop-value%"",""hoverEvent"":{""action"":""show_text"",""value"":{""text"":"""",""extra"":[{""text"":""&3[Shift + Cli%loop-value%""}]}}}"
					execute console command "tellraw %player% [%{_tellraw.emoji.list}%]"
				else:
					send "{@prefix-msg} &cCette commande ne fonctionne qu'avec les émoji &a[ON]"
					send "{@prefix-msg} &eFaites&c,&e /emoji on&c!"
			else:
				send "{@prefix-msg} &cCette commande est désactivée!"
#


on load:#Emoji
	delete {{@prefix}-emoji::*}
	set {{@prefix}-emoji:::bowtie:} to "退"
	set {{@prefix}-emoji::^_^} to "送"
	set {{@prefix}-emoji:::laughing:} to "适"
	set {{@prefix}-emoji::>_<} to "适"
	set {{@prefix}-emoji:::]} to "逃"
	set {{@prefix}-emoji:::D} to "逄"
	set {{@prefix}-emoji:::d} to "逄"
	set {{@prefix}-emoji::c:} to "逅"
	set {{@prefix}-emoji::;]} to "逆"
	set {{@prefix}-emoji::<3_<3} to "逇"
	set {{@prefix}-emoji::kisss} to "逈"
	set {{@prefix}-emoji::kiss} to "选"
	#double way
	set {{@prefix}-emoji::o_o} to "逊"
	set {{@prefix}-emoji:::relieved:} to "逋"
	set {{@prefix}-emoji:::satisfied:} to "逌"
	set {{@prefix}-emoji:::grin:} to "逍"
	set {{@prefix}-emoji::;)} to "逎"
	set {{@prefix}-emoji::;p} to "逐"
	set {{@prefix}-emoji::;d} to "逑"
	set {{@prefix}-emoji::;P} to "逐"
	set {{@prefix}-emoji::;D} to "逑"
	set {{@prefix}-emoji:::)} to "递"
	set {{@prefix}-emoji:::3} to "逓"
	set {{@prefix}-emoji::;3} to "途"
	#double way
	set {{@prefix}-emoji:::P} to "逕"
	set {{@prefix}-emoji:::p} to "逕"
	set {{@prefix}-emoji:::z} to "逖"
	set {{@prefix}-emoji:::worried:} to "逗"
	#double wai
	set {{@prefix}-emoji:::(} to "逘"
	set {{@prefix}-emoji:::frowning:} to "逘"
	set {{@prefix}-emoji::D:} to "這"
	set {{@prefix}-emoji:::oo} to "通"
	set {{@prefix}-emoji:::o} to "遭"
	set {{@prefix}-emoji:::x} to "遮"
	set {{@prefix}-emoji::Skype} to "適"
	set {{@prefix}-emoji::skype} to "適"
	set {{@prefix}-emoji::hhhh} to "逛"
	set {{@prefix}-emoji:::s} to "逜"
	set {{@prefix}-emoji:::hushed:} to "逝"
	set {{@prefix}-emoji::-_-} to "逞"
	set {{@prefix}-emoji:::/} to "速"
	set {{@prefix}-emoji::':D:} to "造"
	#'
	set {{@prefix}-emoji::':(} to "逡"
	#'
	set {{@prefix}-emoji:::disappointed_relieved:} to "逢"
	set {{@prefix}-emoji:::weary:} to "連"
	set {{@prefix}-emoji::v_v} to "逤"
	set {{@prefix}-emoji:::disappointed:} to "逥"
	set {{@prefix}-emoji::>_<} to "逦"
	set {{@prefix}-emoji:::fearful:} to "逧"
	set {{@prefix}-emoji:::cold_sweat:} to "逨"
	set {{@prefix}-emoji::>n<} to "逩"
	set {{@prefix}-emoji:::'(} to "逪"
	#'
	#double way
	set {{@prefix}-emoji::;(} to "逫"
	set {{@prefix}-emoji::D':} to "逫"
	#'
	set {{@prefix}-emoji:::'D} to "逬"
	#'
	set {{@prefix}-emoji::xnx} to "逭"
	set {{@prefix}-emoji::x_x} to "逭"
	set {{@prefix}-emoji::""_""} to "逭"
	set {{@prefix}-emoji::OnO} to "逮"
	set {{@prefix}-emoji:::neckbeard:} to "逯"
	set {{@prefix}-emoji::>-<} to "逰"
	set {{@prefix}-emoji::>:(} to "週"
	set {{@prefix}-emoji::>>:(} to "進"
	set {{@prefix}-emoji:::triumph:} to "逳"
	set {{@prefix}-emoji:::sleepy:} to "逴"
	set {{@prefix}-emoji:::)P} to "逵"
	set {{@prefix}-emoji::Apple:x} to "逶"
	set {{@prefix}-emoji::8)} to "逷"
	set {{@prefix}-emoji::xox} to "逸"
	set {{@prefix}-emoji:::imp:} to "逹"
	set {{@prefix}-emoji:::smiling_imp:} to "逺"
	set {{@prefix}-emoji:::|} to "逻"
	set {{@prefix}-emoji:::no_mouth:} to "逼"
	set {{@prefix}-emoji::0:)} to "逽"
	set {{@prefix}-emoji::(8]} to "逾"
	set {{@prefix}-emoji:::yellow_heart:} to "逿"
	set {{@prefix}-emoji:::blue_heart:} to "遀"
	set {{@prefix}-emoji:::purple_heart:} to "遁"
	set {{@prefix}-emoji::<3} to "遂"
	set {{@prefix}-emoji:::green_heart:} to "遃"
	set {{@prefix}-emoji::</3:} to "遄"
	set {{@prefix}-emoji:::heartbeat:} to "遅"
	set {{@prefix}-emoji::<333} to "遆"
	set {{@prefix}-emoji::<33} to "遇"
	set {{@prefix}-emoji::<3<3} to "遈"
	set {{@prefix}-emoji::-<3->} to "遉"
	set {{@prefix}-emoji::""<3""} to "遊"
	set {{@prefix}-emoji::""""} to "運"
	set {{@prefix}-emoji::[X]} to "遌"
	set {{@prefix}-emoji::[""X""]} to "遍"
	set {{@prefix}-emoji::[O]} to "過"
	set {{@prefix}-emoji:::explo} to "遏"
	set {{@prefix}-emoji:::anger:} to "遐"
	set {{@prefix}-emoji::[!]} to "遑"
	set {{@prefix}-emoji::[?]} to "遒"
	set {{@prefix}-emoji::[!""]} to "道"
	set {{@prefix}-emoji::[?""]} to "達"
	set {{@prefix}-emoji::zzz} to "違"
	set {{@prefix}-emoji:::dash:} to "遖"
	set {{@prefix}-emoji:::sweat_drops:} to "遗"
	set {{@prefix}-emoji:::notes:} to "遘"
	set {{@prefix}-emoji:::musical_note:} to "遙"
	set {{@prefix}-emoji:::fire:} to "遚"
	set {{@prefix}-emoji:::shit:} to "遛"
	set {{@prefix}-emoji:::miam:} to "透"
	set {{@prefix}-emoji:::+} to "遡"
	set {{@prefix}-emoji:::-} to "遢"
	set {{@prefix}-emoji:::cut} to "遠"
	set {{@prefix}-emoji:::bombe} to "遝"
	set {{@prefix}-emoji:::gun} to "遞"
	set {{@prefix}-emoji:::$} to "遜"
	set {{@prefix}-emoji:::oklm} to "遣"
#
