options:
	prefix: SkUltimateChat
	prefix-msg: %{SkUltimateChat-commandes-prefix}%
	perms: perm.%{SkUltimateChat-permissions-prefix}%
	file: plugins/SkUltimateChat/emoji.txt
#

#	loaded 	= pack activées
#	chat	= chat définis sur émojis
#	enable	= emoji mode on, mais pas forcément loaded donc pas chat

#	Function by Snow-Pyon
function packetRPSend(player: player, url: text, hash: text):
	set {_packet} to new play_server_resource_pack_send packet
	set string pinfo 0 of {_packet} to {_url}
	send {_player} packet {_packet}
#

on packet recieve:
	if event-string is "PacketPlayInResourcePackStatus":
		set {_player} to event-player
		set {_status} to packet field "status"
		if "%{_status}%" = "SUCCESSFULLY_LOADED":
			send "{@prefix-msg} <gold>Émojies &2chargées." to {_player}
			set {{@prefix}.emoji.chat.%player%} to true
			set {{@prefix}.emoji.loaded.%player%} to true
		else if "%{_status}%" = "DECLINED":
			send "{@prefix-msg} <light red>Erreur de chargement des émojis." to {_player}
			
#

on join:
	if {{@prefix}.emoji.enable.%player%} is true:
		packetRPSend(player, "http://www.pwtg.fr/minecraft/PWTG_Pack.zip", "%{{@prefix}.emoji.hash-pack}%")
#
on quit:
	delete {{@prefix}.emoji.loaded.%player%}
	delete {{@prefix}.emoji.chat.%player%}
#


command /emoji [<text>]:
	description: "Change vos préférances d'Emoji!"
	trigger:
		if {{@prefix}.emoji.module-emoji} is not true:
			stop trigger
		else if arg 1 is not set:
			send "&6--&2 Emoji &6--"
			send "&a/emoji &e<on / off / mode>"
			send "&eon&c: &fActive les emojis"
			send "&eoff&c: &fDésactive les emojis"
			send "&emode&c: &fActive/Désactive les emoji à chaque connexions"
			if {{@prefix}.emoji.loaded.%player%} is true:
				if {{@prefix}.emoji.emoji-list} is true:
					send "&eliste&c: &fAffiche la liste des émojis &c& &fpermet de les utiliser"
					send "   &c→→→ pour voir la liste il faut avoir les emoji &a[ON]&c←←←"
		else if arg 1 is "on":
			if {{@prefix}.emoji.wait.%player%} is true:
				send "&cMerci de patienter un peu avant de faire cette commande !"
				stop trigger
			set {{@prefix}.emoji.chat.%player%} to true
			if {{@prefix}.emoji.loaded.%player%} is not set:
				packetRPSend(player, "http://www.pwtg.fr/minecraft/PWTG_Pack.zip", "%{{@prefix}.emoji.hash-pack}%")
			set {{@prefix}.emoji.loaded.%player%} to true
			send "{@prefix-msg} &rVous avez activé les émojis, /emoji liste pour voir la liste."
			ChatSendFull(player, 10)
			set {{@prefix}.emoji.wait.%player%} to true
			wait 30 seconds
			delete {{@prefix}.emoji.wait.%player%}
		else if arg 1 is "off":
			if {{@prefix}.emoji.wait.%player%} is true:
				send "&cMerci de patienter un peu avant de faire cette commande !"
				stop trigger
			delete {{@prefix}.emoji.chat.%player%}
			send "{@prefix-msg} &rVous avez désactivé les émojis."
			ChatSendFull(player, 10)
			set {{@prefix}.emoji.wait.%player%} to true
			wait 30 seconds
			delete {{@prefix}.emoji.wait.%player%}
		else if arg 1 is "mode":
			if {{@prefix}.emoji.enable.%player%} is true:
				delete {{@prefix}.emoji.enable.%player%}
				send "{@prefix-msg} &cEmoji désactivé lors de votre prochainne connexion !"
				send "{@prefix-msg} &cPour les désactiver dès maintenant &e/emoji off"
			else:
				set {{@prefix}.emoji.enable.%player%} to true
				send "{@prefix-msg} &aLes emoji seronts activées à votre prochainne connexion !"
				send "{@prefix-msg} &2Pour les activer dès maintenant &e/emoji on"
		else if arg 1 is "liste" or "list":
			if {{@prefix}.emoji.emoji-list} is true:
				if player has permission "%{{@perms}.emoji.perm.cmd-emoji-list}%":
					if {{@prefix}.emoji.loaded.%player%} is true:
						send "&6--&2 Emoji &6--"
						send "&6Shift&c' &6Cliquez sur une &bémoji&c, &6pour l'ajouter au message&c:"
						set {_tellraw.emoji.list} to "{""text"":""["",""color"":""gold""},{""text"":""Liste"",""color"":""dark_green""},{""text"":""] "",""color"":""gold""}"
						loop {{@prefix}-emoji-normal::*}:
							if "%{_tellraw.emoji.list}%" do not contain "%loop-value%":
								set {_perm} to "%{{@perms}.emoji.perm.perm-emoji-normal}%"
								replace all "<emoji-name>" with "%loop-index%" in {_perm}
								if player has permission "%{_perm}%":
									if "%{_tellraw.emoji.list}%" is not "":
										set {_tellraw.emoji.list} to "%{_tellraw.emoji.list}%,"
									set {_tellraw.emoji.list} to "%{_tellraw.emoji.list}%{""text"":""%loop-value%"",""insertion"":""%loop-value%"",""hoverEvent"":{""action"":""show_text"",""value"":{""text"":"""",""extra"":[{""text"":""<cyan>[Shift + Clique]<red>,<gold> pour mettre <lime>'<white>%loop-value%<lime>'""}]}}}"
						execute console command "tellraw %player% [%{_tellraw.emoji.list}%]"
						if {{@prefix}.emoji.emoji-nsfw} is true:
							set {_tellraw.emoji.list} to "{""text"":""["",""color"":""gold""},{""text"":""NSFW"",""color"":""red""},{""text"":""] "",""color"":""gold""}"
							loop {{@prefix}-emoji-nsfw::*}:
								if "%{_tellraw.emoji.list}%" do not contain "%loop-value%":
									set {_perm} to "%{{@perms}.emoji.perm.perm-emoji-nsfw}%"
									replace all "<emoji-name>" with "%loop-index%" in {_perm}
									if player has permission "%{_perm}%":
										if "%{_tellraw.emoji.list}%" is not "":
											set {_tellraw.emoji.list} to "%{_tellraw.emoji.list}%,"
										set {_tellraw.emoji.list} to "%{_tellraw.emoji.list}%{""text"":""%loop-value%"",""insertion"":""%loop-value%"",""hoverEvent"":{""action"":""show_text"",""value"":{""text"":"""",""extra"":[{""text"":""<cyan>[Shift + Clique]<red>,<gold> pour mettre <lime>'<white>%loop-value%<lime>'""}]}}}"
							execute console command "tellraw %player% [%{_tellraw.emoji.list}%]"
					else:
						send "{@prefix-msg} &cCette commande ne fonctionne qu'avec les émoji &a[ON]"
						send "{@prefix-msg} &eFaites&c,&e /emoji on&c!"
				else:
					send "{@prefix-msg} &cCette commande ne vous ai pas permise!"
			else:
				send "{@prefix-msg} &cCette commande est désactivée!"
#


on load:#Emoji
	delete {{@prefix}-emoji-normal::*}
	set {{@prefix}-emoji-normal:::bowtie:} to "退"
	set {{@prefix}-emoji-normal::^_^} to "送"
	set {{@prefix}-emoji-normal:::laughing:} to "适"
	set {{@prefix}-emoji-normal::>_<} to "适"
	set {{@prefix}-emoji-normal:::]} to "逃"
	set {{@prefix}-emoji-normal:::D} to "逄"
	set {{@prefix}-emoji-normal:::d} to "逄"
	set {{@prefix}-emoji-normal::c:} to "逅"
	set {{@prefix}-emoji-normal::;]} to "逆"
	set {{@prefix}-emoji-normal::<3_<3} to "逇"
	set {{@prefix}-emoji-normal::kisss} to "逈"
	set {{@prefix}-emoji-normal::kiss} to "选"
	#double way
	set {{@prefix}-emoji-normal::o_o} to "逊"
	set {{@prefix}-emoji-normal:::relieved:} to "逋"
	set {{@prefix}-emoji-normal:::satisfied:} to "逌"
	set {{@prefix}-emoji-normal:::grin:} to "逍"
	set {{@prefix}-emoji-normal::;)} to "逎"
	set {{@prefix}-emoji-normal::;p} to "逐"
	set {{@prefix}-emoji-normal::;d} to "逑"
	set {{@prefix}-emoji-normal::;P} to "逐"
	set {{@prefix}-emoji-normal::;D} to "逑"
	set {{@prefix}-emoji-normal:::)} to "递"
	set {{@prefix}-emoji-normal:::3} to "逓"
	set {{@prefix}-emoji-normal::;3} to "途"
	#double way
	set {{@prefix}-emoji-normal:::P} to "逕"
	set {{@prefix}-emoji-normal:::p} to "逕"
	set {{@prefix}-emoji-normal:::z} to "逖"
	set {{@prefix}-emoji-normal:::worried:} to "逗"
	#double wai
	set {{@prefix}-emoji-normal:::(} to "逘"
	set {{@prefix}-emoji-normal:::frowning:} to "逘"
	set {{@prefix}-emoji-normal::D:} to "這"
	set {{@prefix}-emoji-normal:::oo} to "通"
	set {{@prefix}-emoji-normal:::o} to "遭"
	set {{@prefix}-emoji-normal:::x} to "遮"
	set {{@prefix}-emoji-normal::Skype} to "適"
	set {{@prefix}-emoji-normal::skype} to "適"
	set {{@prefix}-emoji-normal::hhhh} to "逛"
	set {{@prefix}-emoji-normal:::s} to "逜"
	set {{@prefix}-emoji-normal:::hushed:} to "逝"
	set {{@prefix}-emoji-normal::-_-} to "逞"
	set {{@prefix}-emoji-normal:::/} to "速"
	set {{@prefix}-emoji-normal::':D:} to "造"
	#'
	set {{@prefix}-emoji-normal::':(} to "逡"
	#'
	set {{@prefix}-emoji-normal:::disappointed_relieved:} to "逢"
	set {{@prefix}-emoji-normal:::weary:} to "連"
	set {{@prefix}-emoji-normal::v_v} to "逤"
	set {{@prefix}-emoji-normal:::disappointed:} to "逥"
	set {{@prefix}-emoji-normal::>_<} to "逦"
	set {{@prefix}-emoji-normal:::fearful:} to "逧"
	set {{@prefix}-emoji-normal:::cold_sweat:} to "逨"
	set {{@prefix}-emoji-normal::>n<} to "逩"
	set {{@prefix}-emoji-normal:::'(} to "逪"
	#'
	#double way
	set {{@prefix}-emoji-normal::;(} to "逫"
	set {{@prefix}-emoji-normal::D':} to "逫"
	#'
	set {{@prefix}-emoji-normal:::'D} to "逬"
	#'
	set {{@prefix}-emoji-normal::xnx} to "逭"
	set {{@prefix}-emoji-normal::x_x} to "逭"
	set {{@prefix}-emoji-normal::""_""} to "逭"
	set {{@prefix}-emoji-normal::OnO} to "逮"
	set {{@prefix}-emoji-normal:::neckbeard:} to "逯"
	set {{@prefix}-emoji-normal::>-<} to "逰"
	set {{@prefix}-emoji-normal::>:(} to "週"
	set {{@prefix}-emoji-normal::>>:(} to "進"
	set {{@prefix}-emoji-normal:::triumph:} to "逳"
	set {{@prefix}-emoji-normal:::sleepy:} to "逴"
	set {{@prefix}-emoji-normal:::)P} to "逵"
	set {{@prefix}-emoji-normal::Apple:x} to "逶"
	set {{@prefix}-emoji-normal::8)} to "逷"
	set {{@prefix}-emoji-normal::xox} to "逸"
	set {{@prefix}-emoji-normal:::imp:} to "逹"
	set {{@prefix}-emoji-normal:::smiling_imp:} to "逺"
	set {{@prefix}-emoji-normal:::|} to "逻"
	set {{@prefix}-emoji-normal:::no_mouth:} to "逼"
	set {{@prefix}-emoji-normal::0:)} to "逽"
	set {{@prefix}-emoji-normal::(8]} to "逾"
	set {{@prefix}-emoji-normal:::yellow_heart:} to "逿"
	set {{@prefix}-emoji-normal:::blue_heart:} to "遀"
	set {{@prefix}-emoji-normal:::purple_heart:} to "遁"
	set {{@prefix}-emoji-normal::<3} to "遂"
	set {{@prefix}-emoji-normal:::green_heart:} to "遃"
	set {{@prefix}-emoji-normal::</3:} to "遄"
	set {{@prefix}-emoji-normal:::heartbeat:} to "遅"
	set {{@prefix}-emoji-normal::<333} to "遆"
	set {{@prefix}-emoji-normal::<33} to "遇"
	set {{@prefix}-emoji-normal::<3<3} to "遈"
	set {{@prefix}-emoji-normal::-<3->} to "遉"
	set {{@prefix}-emoji-normal::""<3""} to "遊"
	set {{@prefix}-emoji-normal::""""} to "運"
	set {{@prefix}-emoji-normal::[X]} to "遌"
	set {{@prefix}-emoji-normal::[""X""]} to "遍"
	set {{@prefix}-emoji-normal::[O]} to "過"
	set {{@prefix}-emoji-normal:::explo} to "遏"
	set {{@prefix}-emoji-normal:::anger:} to "遐"
	set {{@prefix}-emoji-normal::[!]} to "遑"
	set {{@prefix}-emoji-normal::[?]} to "遒"
	set {{@prefix}-emoji-normal::[!""]} to "道"
	set {{@prefix}-emoji-normal::[?""]} to "達"
	set {{@prefix}-emoji-normal::zzz} to "違"
	set {{@prefix}-emoji-normal:::dash:} to "遖"
	set {{@prefix}-emoji-normal:::sweat_drops:} to "遗"
	set {{@prefix}-emoji-normal:::notes:} to "遘"
	set {{@prefix}-emoji-normal:::musical_note:} to "遙"
	set {{@prefix}-emoji-normal:::fire:} to "遚"
	set {{@prefix}-emoji-normal:::shit:} to "遛"
	set {{@prefix}-emoji-normal:::miam:} to "透"
	set {{@prefix}-emoji-normal:::+} to "遡"
	set {{@prefix}-emoji-normal:::-} to "遢"
	set {{@prefix}-emoji-normal:::$} to "遜"
	set {{@prefix}-emoji-normal:::oklm} to "遣"
#
on load:
	if file existance of "{@file}" is true:
		delete file "{@file}"
	wait 1 tick
	create file "{@file}"
	wait 1 tick
	if {{@prefix}.emoji.emoji-nsfw} is true:
		set {{@prefix}-emoji-nsfw:::cut} to "遠"
		set {{@prefix}-emoji-nsfw:::bombe} to "遝"
		set {{@prefix}-emoji-nsfw:::gun} to "遞"
		loop {{@prefix}-emoji-nsfw::*}:
			set {_perm} to "%{{@perms}.emoji.perm.perm-emoji-nsfw}%"
			replace all "<emoji-name>" with "%loop-index%" in {_perm}
			write " - ""%loop-index%"" -> permission: %{_perm}%" at line 1 to file "{@file}"
			wait 1 tick
		write "##" at line 1 to file "{@file}"
		set {_perm} to "%{{@perms}.emoji.perm.perm-emoji-nsfw}%"
		replace all "<emoji-name>" with "*" in {_perm}
		write "%{_perm}% = full NSFW permissions" at line 1 to file "{@file}"
		write "##" at line 1 to file "{@file}"
		write "NSFW emojis:" at line 1 to file "{@file}"
		write "##" at line 1 to file "{@file}"
	loop {{@prefix}-emoji-normal::*}:
		if "%loop-index%" do not contain "$":
			set {_perm} to "%{{@perms}.emoji.perm.perm-emoji-normal}%"
			replace all "<emoji-name>" with "%loop-index%" in {_perm}
			write " - ""%loop-index%"" -> permission: %{_perm}%" at line 1 to file "{@file}"
			wait 1 tick
	write "##" at line 1 to file "{@file}"
	set {_perm} to "%{{@perms}.emoji.perm.perm-emoji-normal}%"
	replace all "<emoji-name>" with "*" in {_perm}
	write "%{_perm}% = full permissions" at line 1 to file "{@file}"
	write "##" at line 1 to file "{@file}"
	write "Emojis:" at line 1 to file "{@file}"
#
